package com.testspace4.kafkapushdepen;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class caseSRDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String requestSubType;
	private java.lang.String requestType;
	private com.testspace4.kafkapushdepen.SRDto srRequest;

	public caseSRDto() {
	}

	public java.lang.String getRequestSubType() {
		return this.requestSubType;
	}

	public void setRequestSubType(java.lang.String requestSubType) {
		this.requestSubType = requestSubType;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public com.testspace4.kafkapushdepen.SRDto getSrRequest() {
		return this.srRequest;
	}

	public void setSrRequest(com.testspace4.kafkapushdepen.SRDto srRequest) {
		this.srRequest = srRequest;
	}

	public caseSRDto(java.lang.String requestSubType,
			java.lang.String requestType,
			com.testspace4.kafkapushdepen.SRDto srRequest) {
		this.requestSubType = requestSubType;
		this.requestType = requestType;
		this.srRequest = srRequest;
	}

}