package com.testspace4.kafkapushdepen;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PayloadObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date time;
	private java.lang.String source;
	private java.lang.String type;
	private java.lang.Double id;

	private java.lang.String specversion;

	public PayloadObject() {
	}

	public java.util.Date getTime() {
		return this.time;
	}

	public void setTime(java.util.Date time) {
		this.time = time;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Double getId() {
		return this.id;
	}

	public void setId(java.lang.Double id) {
		this.id = id;
	}

	public java.lang.String getSpecversion() {
		return this.specversion;
	}

	public void setSpecversion(java.lang.String specversion) {
		this.specversion = specversion;
	}

	public PayloadObject(java.util.Date time, java.lang.String source,
			java.lang.String type, java.lang.Double id,
			java.lang.String specversion) {
		this.time = time;
		this.source = source;
		this.type = type;
		this.id = id;
		this.specversion = specversion;
	}

}