package com.testspace4.kafkapushdepen;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SRDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Long srNumber;
	private java.lang.String caseNumber;
	private java.lang.String channel;

	private java.lang.String requestType;

	private java.lang.String srUUID;

	public SRDto() {
	}

	public java.lang.String getCaseNumber() {
		return this.caseNumber;
	}

	public void setCaseNumber(java.lang.String caseNumber) {
		this.caseNumber = caseNumber;
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public java.lang.String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(java.lang.String requestType) {
		this.requestType = requestType;
	}

	public java.lang.Long getSrNumber() {
		return this.srNumber;
	}

	public void setSrNumber(java.lang.Long srNumber) {
		this.srNumber = srNumber;
	}

	public java.lang.String getSrUUID() {
		return this.srUUID;
	}

	public void setSrUUID(java.lang.String srUUID) {
		this.srUUID = srUUID;
	}

	public SRDto(java.lang.Long srNumber, java.lang.String caseNumber,
			java.lang.String channel, java.lang.String requestType,
			java.lang.String srUUID) {
		this.srNumber = srNumber;
		this.caseNumber = caseNumber;
		this.channel = channel;
		this.requestType = requestType;
		this.srUUID = srUUID;
	}

}