package com.testspace4.kafkapushdepen;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class user implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String id;

	private java.lang.Integer workingTickets;

	private java.lang.Integer age;

	private java.lang.String role;

	public user() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getWorkingTickets() {
		return this.workingTickets;
	}

	public void setWorkingTickets(java.lang.Integer workingTickets) {
		this.workingTickets = workingTickets;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public user(java.lang.String name, java.lang.String id,
			java.lang.Integer workingTickets, java.lang.Integer age,
			java.lang.String role) {
		this.name = name;
		this.id = id;
		this.workingTickets = workingTickets;
		this.age = age;
		this.role = role;
	}

}