package com.testspace4.kafkapushdepen;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UserData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.testspace4.kafkapushdepen.user data;

	public UserData() {
	}

	public com.testspace4.kafkapushdepen.user getData() {
		return this.data;
	}

	public void setData(com.testspace4.kafkapushdepen.user data) {
		this.data = data;
	}

	public UserData(com.testspace4.kafkapushdepen.user data) {
		this.data = data;
	}

}